---
networks:
  macvlan_network:
    external: true
    name: "${DOCKER_NETWORK}"

services:
  audiobooks-setup:
    build: ./build/
    image: audiobooks-setup
    pull_policy: build
    container_name: audiobooks-setup
    volumes:
      - "${SSL}:/ssl"
      - "${NGINX}:/nginx"
    env_file:
      - ./private/.env

  nginx:
    image: nginx:latest
    pull_policy: always
    container_name: audiobooks-nginx
    restart: always
    volumes:
      - "${NGINX}/nginx.conf:/etc/nginx/nginx.conf"
      - "${SSL}:/ssl"
    networks:
      macvlan_network:
        ipv4_address: "${IP_ADDRESS}"
    depends_on:
      audiobooks-setup:
        condition: service_completed_successfully

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    pull_policy: always
    container_name: "audiobooks-qbittorrent"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
      - "WEBUI_PORT=8080"
    restart: always
    network_mode: "service:nginx"
    volumes:
      - "${QBITTORRENT_CONFIG}:/config"
      - "${DOWNLOADS}:/downloads"
    depends_on:
      nginx:
        condition: service_started
