services:
  audiobooks-setup:
    build: ./build/
    image: audiobooks-setup
    pull_policy: build
    container_name: audiobooks-setup
    volumes:
      - "${SSL}:/ssl"
      - "${NGINX}:/nginx"
    env_file:
      - ./private/.env

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    pull_policy: always
    container_name: "audiobooks-qbittorrent"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
      - "WEBUI_PORT=8080"
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - "${QBITTORRENT_CONFIG}:/config"
      - "${DOWNLOADS}:/downloads"
    depends_on:
      audiobooks-setup:
        condition: service_completed_successfully
